# Generated by Django 4.2.2 on 2023-07-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('marke', models.CharField(max_length=255)),
                ('modelis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('valstybinis_numeris', models.CharField(max_length=20)),
                ('vin_kodas', models.CharField(max_length=17)),
                ('klientas', models.CharField(max_length=255)),
                ('automobilio_modelis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.automobiliomodelis')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite knygos žanrą (pvz. detektyvas)', max_length=200, verbose_name='Pavadinimas')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pavadinimas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=255)),
                ('suma', models.CharField(max_length=255)),
                ('pavadinimas', models.CharField(max_length=255)),
                ('kaina', models.IntegerField()),
                ('automobilis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.automobilis')),
            ],
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kiekis', models.CharField(max_length=255)),
                ('kaina', models.CharField(max_length=255)),
                ('paslauga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.paslauga')),
                ('uzsakymas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.uzsakymas')),
            ],
        ),
    ]
