# Generated by Django 4.2.2 on 2023-07-03 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='paslauga',
            name='datetime_now',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
