# Generated by Django 4.2.2 on 2023-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0005_alter_uzsakymas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
