# Generated by Django 4.2.2 on 2023-07-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_alter_uzsakymas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymas',
            name='statusas',
            field=models.CharField(choices=[('N', 'Naujas'), ('V', 'Vykdomas'), ('U', 'Užbaigtas'), ('A', 'Atšauktas')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.CharField(max_length=255),
        ),
    ]
