# Generated by Django 4.2.2 on 2023-07-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0007_uzsakymas_statusas_alter_uzsakymas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
