# Generated by Django 4.2.2 on 2023-07-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0008_alter_uzsakymas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
