# Generated by Django 4.2.2 on 2023-07-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0009_automobilis_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='resized_cover',
            field=models.ImageField(blank=True, null=True, upload_to='resized_covers', verbose_name='Viršelis (Resized)'),
        ),
    ]
