# Generated by Django 4.2.2 on 2023-07-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0011_automobilis_vartotojas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilis',
            old_name='vartotojas',
            new_name='reader',
        ),
        migrations.AddField(
            model_name='automobilis',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('pending', 'Pending')], default='available', max_length=20),
        ),
    ]
