# Generated by Django 4.2.2 on 2023-07-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0012_rename_vartotojas_automobilis_reader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
