# Generated by Django 4.2.2 on 2023-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0016_remove_automobiliomodelis_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='description',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
