# Generated by Django 4.2.2 on 2023-07-13 10:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0017_alter_automobilis_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
