# Generated by Django 4.2.2 on 2023-07-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0020_profilis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilis',
            name='nuotrauka',
            field=models.ImageField(default='img/noimg.jpg', upload_to='profile_pics'),
        ),
    ]
