# Generated by Django 4.2.2 on 2023-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0021_alter_profilis_nuotrauka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilis',
            name='nuotrauka',
            field=models.ImageField(default='img/no-img.png', upload_to='profile_pics'),
        ),
    ]
